### ISSUE TITLE
Translation will appear for once

### ISSUE THREAD

**Issue by mkwsra** [xinax/laravel-gettext#13]
Hey there, I really appreciate your work, this library is greate, and I'd like to share my issue:

I've 5 languages and I'm using my own Language selector inside it, I'm calling your function `LaravelGettext::setLocale($currentCode);` when I change language, however, the translations appeared  ONLY if I opened English first and then e.g Germen! everything is find.
but if I click on Arabic or on Germen again! the texts will get  back to English!!!

and I really don't know why, I did the following:
restarted apache.
reloaded vagrant.
made sure the setting are right and the values of domain,coding...etc are right!

I don't think that this issue had to do with caching, maybe I don't need to hard code putevn, but without it it don't appear at all.

**Comment by shaggyz** [comment]
It seems like you forgot set the package middleware:

>In Laravel 5 you also need to register the LaravelGettext middleware in the app/Http/Kernel.php file:

```php
    protected $middleware = [
        ...
        'Xinax\LaravelGettext\Middleware\GettextMiddleware',
    ]
```
If middleware is ok, please run unit tests and share your results. The translation features are strongly tested, also check that your redirections are ok.

And finally your system must have installed the needed locales. Ex: If your app uses the locale de_DE, the locale de_DE must be installed in your system.

All this information is on documentation. Please read it before fill an issue, this is not a support area.

**Comment by mkwsra** [comment]
For sure, I've read the documentation more than 3 times and the middleware is in its place I'm not an idiot to forget it or don't install Locale in the system, I've run locale -a :
```
$ locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
ar_AE.utf8
C
C.UTF-8
de_DE.utf8
en_US.utf8
nl_NL.utf8
POSIX
tr_TR.utf8
```
and I know this is not a support area. Thanks for your reply! I just wanted to share my issue because I've tried almost everything to solve it

**Comment by shaggyz** [comment]
Ok chill out, there is no problem. Without see your code/logs/debugs I can't help you so much. This package is really simple. Have you tried this?:

1- Run the unit test, it is not infalible but must be the first thing to do. If this fails, something in your system is in conflict with the package and the tests will tell you what is it.

2- Debug the session data: 

```php
dd(Session::all());
``` 
or something like that, and see what happens the first time, then compare with the second language change attempt. The package session values must be persistent, if not, here is your problem.

3- Hack the Gettext class, check the language code that takes the setenv function: 
```php
dd($gettextLocale);
putenv("LC_ALL=$gettextLocale");
```
Here is the php-gettext call, there is nothing more beyond this.

4- Check laravel and apache logs, many times non-catched exceptions are dumped here.

5- At this point, you must divide you problem in small isolated problems. Create a new empty laravel project, install the laravel-gettext package with 2 languages or more, setup, fill some translations and test following the guid in the docs.

And finally, after this debugging work if you find the error *in the package* report the issue, it will be fixed, but remember to share at least a piece of code, logs, debug dumps or something, like another successfull issue reports.

In my opinion, there is something wrong in your code, otherwise we'd have a lot of reports of this big issue, but you know, always can be a bug.

Don't give up developer! Cheers!

**Comment by mkwsra** [comment]
I just wanted your help, please read the following:
1. the phpunit test was:
`Cannot open file "/var/www/ht5/vendor/xinax/laravel-gettext/vendor/autoload.php".`
2. Session content:
```
array:4 [▼
  "_token" => "BAr1jfL2BlwePEhkvbJFDDGCMEaN2OQa4erNzIuV"
  "laravel-gettext-locale" => "en_US"
  "_previous" => array:1 [▼
    "url" => "http://ht5.dev/en/hotels"
  ]
  "flash" => array:2 [▶]
]
```
I've tried it with another language it, the "laravel-gettext-locale" was changed into "de_DE".
Deos the lines above conatians    ` The package session values`
3. the `dd($gettextLocale);` output `"de_DE.UTF-8"`
4. They are fine, apache is empty, laravel log contians other old errors.
5. I will do it now

@shaggyz Thanks a lot for this nice reply, and I will take your advice I won't give up, I've been trying for 5 days with no use and I couldn't determine why! wish you a nice day, regards!
