### ISSUE TITLE
Language reverts back to en_US translation, even though locale is set as da_DK

### ISSUE THREAD

**Issue by canfiax** [xinax/laravel-gettext#58]
I have started creating a few tests using this library. So far, it seems really awesome, so good job!

However I experience some strange issues. To test it out, I have translated a string on my landing page, from en_US to da_DK. I have only translated the da_DK po file.

But when I view the page, even though `getLocale()` is `da_DK` it shows the english translation. If I clear cache using `php artisan cache:clear` it shows the `da_DK` translation as expected. If I refresh once more, the english translation is shown???

I have not implemented the default middleware as instructed by the installation docs, however, I have tried doing so, and same issue persists. Below is my middleware, that is loaded AFTER start session. Is there anything wrong with taking this approach?

    <?php

    namespace App\Http\Middleware;

    use Closure;

    use Carbon\Carbon;
    use \Clicknow\Money\Money;

    class Locale
    {
        /**
         * Convert browser languages
         *
         * @array $languages
         */

        protected $convert = [
            'da' => 'da_DK',
            'en' => 'en_US'
        ];

        /**
         * Handle an incoming request.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  \Closure  $next
         * @return mixed
         */
        public function handle($request, Closure $next)
        {

            /**
             * Get locale string
             * @var [type]
             */

                $locale = $request->cookie('language');

            /**
             * If no locale string, check for browser accept language
             */
            
                if(!$locale) {
                    $lang = substr($request->server('HTTP_ACCEPT_LANGUAGE'), 0, 2); // i.e. "da"

                    if($lang && isset($this->convert[$lang]))
                        $locale = $this->convert[$lang];

                }

            /**
             * Ensure language is supported
             */

            
                if(!in_array($locale, config('laravel-gettext.supported-locales')))
                    $locale = config('app.locale');

            /**
             * Set locale
             */

                app()->setLocale($locale);
                Money::setLocale($locale);
                \LaravelGettext::setLocale($locale);
                Carbon::setLocale(\LaravelGettext::getLocaleLanguage());

            return $next($request)->withCookie('language', $locale);
        }
    }

I am running php7 and homestead.

**Comment by canfiax** [comment]
Continued here: https://github.com/xinax/laravel-gettext/issues/61

**Comment by Gummibeer** [comment]
Have you debuged this? Could it be that there is no cookie and that's why it's using the browser language?
A helpfull link could be: http://mydnic.be/post/laravel-5-and-his-fcking-non-persistent-app-setlocale

I'm not 100% shure if the `withCookie` method works like you expect it - try using the cookie `forever` method to generate a cookie that's lasting for 5 years.
http://stackoverflow.com/questions/34728924/setting-cookie-in-laravel-custom-middleware
https://laravel.com/docs/5.1/responses#attaching-cookies-to-responses
https://laravel.com/docs/5.1/requests#cookies

**Comment by canfiax** [comment]
I have debugged this a lot @Gummibeer - in fact, hours of debugging - I'm confident this is a bug related to the package.

**Comment by Gummibeer** [comment]
@canfiax but you set the locale in the middleware and the package does everything right - related to the php buggy gettext.
have you debuged the `setLocale` https://github.com/xinax/laravel-gettext/blob/master/src/Xinax/LaravelGettext/Gettext.php#L84

in some steps to see how often it is called and what it is doing?

But I can confirm this bug - but for us it was gettext related cause it also didn't work with plain gettext. That's why I've written the wrapper for the Symfony Translator that's not using plain gettext but normal php arrays and so on.
So it has no po/mo & gettext caching problems, it is understandable what's going in in the background and it's fast enough.
https://github.com/xinax/laravel-gettext/issues/45#issuecomment-158068357

Try to implement this class yourself and test it again with the new Symfony wrapper - for us it worked like a charm and is a great compromise between the laravel array translation and translating with self generating po files. so we have the best out of both.^^

Tell me, if you test it, if it's working or if you have to adjust something - this will help implementing this new translating way in the package itself.

**Comment by canfiax** [comment]
Well, I'd actually prefer using gettext, because of the many tools available out there (online translators, etc), and because of performance. I could imagine using arrays in a big application could cause a lot of overhead. Or?

We've already spent quite some time translating our current 830 strings. How could we move that to the Symfony setup?

**Comment by Gummibeer** [comment]
The Symfony translator uses also po files - it also can handle mo, xlif and some more (but not in my class). So your setup would be the same - the only thing would be that it uses `__()` and not `_()` as the translation method - so a global replace will help.
And the overhead and big application: We also have some hundred translations and no difference to normal gettext in performance. But I haven't done a performance test - so I can't tell you if there are differences of some microseconds or not.

All in all, how I read it, this package will be updated to use the symfony translator, like laravel does it. So earlier or later the normal gettext will be thrown away. In my opinion, like it should be, cause it's crap.

**Comment by canfiax** [comment]
great @Gummibeer sounds really good.

Can't wait to see how the Symfony translator will work out. Currently we'll be using the crappy gettext version, and switch to Symfony translator once this package supports .po/.mo files.
